-- Generated by `pnpm db:sql` from packages/db/migrations. Do not edit by hand.
-- Paste into Supabase > SQL Editor and run. Safe to run more than once:
-- migrations already recorded are skipped, and the seed never overwrites edits.

CREATE SCHEMA IF NOT EXISTS drizzle;
CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint);

-- Migration 0000_init
DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM drizzle.__drizzle_migrations WHERE created_at = 1791104603065) THEN
    EXECUTE $sql$
CREATE TYPE "public"."budget_confidence" AS ENUM('high', 'medium', 'low');
CREATE TYPE "public"."budget_type" AS ENUM('fixed', 'hourly', 'unknown');
CREATE TYPE "public"."match_outcome" AS ENUM('rejected', 'below_threshold', 'matched', 'error');
CREATE TYPE "public"."match_status" AS ENUM('new', 'saved', 'applied', 'won', 'lost', 'dismissed');
CREATE TYPE "public"."run_status" AS ENUM('queued', 'running', 'succeeded', 'failed');
CREATE TYPE "public"."run_trigger" AS ENUM('schedule', 'manual', 'cli');
CREATE TABLE "agents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"schedule_interval_minutes" integer DEFAULT 30 NOT NULL,
	"sources" text[] DEFAULT ARRAY['upwork','hn']::text[] NOT NULL,
	"filters" jsonb NOT NULL,
	"offers" jsonb NOT NULL,
	"weights" jsonb NOT NULL,
	"score_threshold" real DEFAULT 6 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agents_name_unique" UNIQUE("name")
);

ALTER TABLE "agents" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "app_settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"data" jsonb NOT NULL,
	"updated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "app_settings_singleton" CHECK ("app_settings"."id" = 1)
);

ALTER TABLE "app_settings" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "job_matches" (
	"job_id" uuid NOT NULL,
	"agent_id" uuid NOT NULL,
	"run_id" uuid,
	"outcome" "match_outcome" NOT NULL,
	"filter_reasons" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"unknown_fields" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"matched_offer" text,
	"fit_score" real,
	"reasoning" text,
	"red_flags" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"failure_case" text,
	"opener" text,
	"est_hours_low" real,
	"est_hours_high" real,
	"complexity" integer,
	"est_duration_days" real,
	"budget_confidence" "budget_confidence",
	"effective_rate" double precision,
	"total_pay" double precision,
	"priority" real,
	"priority_components" jsonb,
	"priority_computed_at" timestamp with time zone,
	"status" "match_status" DEFAULT 'new' NOT NULL,
	"status_changed_by" text,
	"status_changed_at" timestamp with time zone,
	"model" text,
	"input_tokens" integer,
	"output_tokens" integer,
	"scored_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "job_matches_job_id_agent_id_pk" PRIMARY KEY("job_id","agent_id")
);

ALTER TABLE "job_matches" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source" text NOT NULL,
	"external_id" text NOT NULL,
	"url" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"skills" text[] DEFAULT ARRAY[]::text[] NOT NULL,
	"budget_type" "budget_type" DEFAULT 'unknown' NOT NULL,
	"budget_min" double precision,
	"budget_max" double precision,
	"payment_verified" boolean,
	"client_total_spend" double precision,
	"client_hires" integer,
	"client_rating" real,
	"client_country" text,
	"proposal_count" integer,
	"posted_at" timestamp with time zone,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"raw" jsonb
);

ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "match_status_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job_id" uuid NOT NULL,
	"agent_id" uuid NOT NULL,
	"from_status" "match_status",
	"to_status" "match_status" NOT NULL,
	"changed_by" text NOT NULL,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "match_status_events" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"agent_id" uuid NOT NULL,
	"status" "run_status" DEFAULT 'queued' NOT NULL,
	"trigger" "run_trigger" DEFAULT 'schedule' NOT NULL,
	"requested_by" text,
	"queued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"heartbeat_at" timestamp with time zone,
	"fetched" integer DEFAULT 0 NOT NULL,
	"new_jobs" integer DEFAULT 0 NOT NULL,
	"filtered" integer DEFAULT 0 NOT NULL,
	"scored" integer DEFAULT 0 NOT NULL,
	"matched" integer DEFAULT 0 NOT NULL,
	"errors" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"cost_usd" double precision DEFAULT 0 NOT NULL,
	"config_snapshot" jsonb
);

ALTER TABLE "runs" ENABLE ROW LEVEL SECURITY;
CREATE TABLE "user_state" (
	"email" text PRIMARY KEY NOT NULL,
	"jobs_last_seen_at" timestamp with time zone,
	"jobs_prev_seen_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "user_state" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_job_id_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."jobs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "job_matches" ADD CONSTRAINT "job_matches_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."runs"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "runs" ADD CONSTRAINT "runs_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "job_matches_agent_outcome_priority_idx" ON "job_matches" USING btree ("agent_id","outcome","priority" DESC NULLS LAST);
CREATE INDEX "job_matches_status_idx" ON "job_matches" USING btree ("agent_id","status");
CREATE UNIQUE INDEX "jobs_source_external_id_idx" ON "jobs" USING btree ("source","external_id");
CREATE INDEX "jobs_posted_at_idx" ON "jobs" USING btree ("posted_at");
CREATE INDEX "match_status_events_match_idx" ON "match_status_events" USING btree ("job_id","agent_id","changed_at");
CREATE INDEX "runs_agent_queued_idx" ON "runs" USING btree ("agent_id","queued_at" DESC NULLS LAST);
CREATE INDEX "runs_status_idx" ON "runs" USING btree ("status","queued_at");
CREATE UNIQUE INDEX "runs_one_active_per_agent_idx" ON "runs" USING btree ("agent_id") WHERE "runs"."status" in ('queued', 'running');
    $sql$;
    INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('a0dd784d826c4d3a2ace4d9605ea22853670178a37e207b110e0b9594db2ae60', 1791104603065);
  END IF;
END $migration$;

-- Migration 0001_revoke_public_access
DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM drizzle.__drizzle_migrations WHERE created_at = 1791104610052) THEN
    EXECUTE $sql$
-- Defense in depth on top of RLS (enabled with no policies on every table):
-- Supabase's anon and authenticated roles get no privileges on our tables at all,
-- including tables created later. The app connects as the table owner, which RLS does not restrict.
-- Guarded so it no-ops on plain Postgres (tests, local) where these roles don't exist.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
    END IF;
  END LOOP;
END $$;

    $sql$;
    INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('e4a2f6e62509074abd0444036727e4ffc629519421e040c098560ebb6cc21a8f', 1791104610052);
  END IF;
END $migration$;

-- Migration 0002_integration_tokens
DO $migration$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM drizzle.__drizzle_migrations WHERE created_at = 1791104887888) THEN
    EXECUTE $sql$
CREATE TABLE "integration_tokens" (
	"provider" text PRIMARY KEY NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"expires_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "integration_tokens" ENABLE ROW LEVEL SECURITY;
    $sql$;
    INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('dc955926538128bc0326b6e5d46e6d777d4c8cbfa257ba0f7cfa38ed01b3c67c', 1791104887888);
  END IF;
END $migration$;

-- Seed: global settings and the default agent (skipped if they already exist)
INSERT INTO app_settings (id, data, updated_by) VALUES (1, $json${"priority":{"rateFloor":40,"rateTarget":150,"payFloor":500,"payTarget":20000,"durationBestDays":5,"durationWorstDays":45,"competitionMaxProposals":20,"freshnessHalfLifeHours":12,"unknownNeutral":0.4},"scoring":{"model":"claude-haiku-4-5-20251001","agencyProfile":"We are a two-engineer freelance coding agency. Both engineers previously built self-driving software at GM, so we are strong on production backend systems, data pipelines, integrations and applied AI. We prefer well-scoped projects we can ship quickly for clients who value quality.","extraInstructions":"","maxConcurrency":4,"maxOutputTokens":1500,"maxJobsPerRun":60,"inputCostPerMTok":1,"outputCostPerMTok":5},"runs":{"allowManualRunWhenPaused":true,"freshnessRescoreMinutes":15,"staleRunMinutes":10},"sources":{"upworkMode":"auto","upworkSearchQueries":["AI chatbot","workflow automation","Zapier OR Make OR n8n","Conversions API","server side tracking","OpenAI integration","LLM"],"hnEnabled":true}}$json$::jsonb, 'seed') ON CONFLICT (id) DO NOTHING;
INSERT INTO agents (name, enabled, schedule_interval_minutes, sources, filters, offers, weights, score_threshold) VALUES ('Default agent', true, 30, ARRAY['upwork','hn'], $json${"requirePaymentVerified":true,"minClientSpend":10000,"hireSanity":{"minHires":5,"minSpendPerHire":500},"minFixedBudget":500,"minHourlyRate":40,"maxProposals":20,"maxAgeHours":48,"excludedKeywords":["starter project","unpaid","test task","equity only","free trial"]}$json$::jsonb, $json$[{"key":"ai_support_bot","title":"AI support bot","description":"A chatbot that answers customer or internal questions from the client's own docs (help center, PDFs, Notion, website). Retrieval over their content, citations, handoff to a human."},{"key":"workflow_automation","title":"Workflow automation","description":"Connecting CRM, email, forms, Google Sheets and Slack, with AI steps for sorting, enriching, summarizing and drafting. Zapier/Make/n8n or custom code."},{"key":"server_side_tracking","title":"Server side tracking","description":"Meta Conversions API (CAPI), TikTok Events API, Google Ads enhanced conversions, server side Google Tag Manager, deduplication and consent handling."},{"key":"ai_feature","title":"AI feature for an existing app","description":"Adding an LLM-powered feature to an existing web or mobile product: summarization, extraction, classification, semantic search, assistants, with evals and cost control."}]$json$::jsonb, $json${"rate":25,"pay":15,"complexity":10,"duration":10,"fit":25,"competition":8,"freshness":7}$json$::jsonb, 6) ON CONFLICT (name) DO NOTHING;
