/**
 * Writes supabase/setup.sql: every migration plus the seed, as one script to paste into the
 * Supabase SQL Editor. It also records the migrations in drizzle's journal table, so the
 * worker's automatic migrations (or `pnpm db:migrate`) later skip what was already applied.
 *
 *   pnpm db:sql   (rerun after adding a migration, and commit the output)
 */
import { DEFAULT_WEIGHTS } from "@jf/scoring";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { AgentFiltersSchema, DEFAULT_GLOBAL_SETTINGS, DEFAULT_OFFERS } from "./config";
import { DEFAULT_AGENT_NAME } from "./seed-data";

const migrationsDir = fileURLToPath(new URL("../migrations/", import.meta.url));
const outDir = fileURLToPath(new URL("../../../supabase/", import.meta.url));

interface Journal {
  entries: { idx: number; when: number; tag: string }[];
}
const journal = JSON.parse(readFileSync(`${migrationsDir}meta/_journal.json`, "utf8")) as Journal;
const json = (v: unknown) => `$json$${JSON.stringify(v)}$json$::jsonb`;

const parts: string[] = [
  "-- Generated by `pnpm db:sql` from packages/db/migrations. Do not edit by hand.",
  "-- Paste into Supabase > SQL Editor and run. Safe to run more than once:",
  "-- migrations already recorded are skipped, and the seed never overwrites edits.",
  "",
  "CREATE SCHEMA IF NOT EXISTS drizzle;",
  "CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint);",
  "",
];

for (const entry of journal.entries) {
  // Same hash drizzle's migrator computes, so it recognizes these as applied.
  const sql = readFileSync(`${migrationsDir}${entry.tag}.sql`, "utf8");
  const hash = createHash("sha256").update(sql).digest("hex");
  parts.push(
    `-- Migration ${entry.tag}`,
    `DO $migration$`,
    `BEGIN`,
    `  IF NOT EXISTS (SELECT 1 FROM drizzle.__drizzle_migrations WHERE created_at = ${entry.when}) THEN`,
    `    EXECUTE $sql$`,
    sql.replace(/--> statement-breakpoint/g, ""),
    `    $sql$;`,
    `    INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('${hash}', ${entry.when});`,
    `  END IF;`,
    `END $migration$;`,
    "",
  );
}

parts.push(
  "-- Seed: global settings and the default agent (skipped if they already exist)",
  `INSERT INTO app_settings (id, data, updated_by) VALUES (1, ${json(DEFAULT_GLOBAL_SETTINGS)}, 'seed') ON CONFLICT (id) DO NOTHING;`,
  `INSERT INTO agents (name, enabled, schedule_interval_minutes, sources, filters, offers, weights, score_threshold) VALUES (` +
    `'${DEFAULT_AGENT_NAME}', true, 30, ARRAY['upwork','hn'], ${json(AgentFiltersSchema.parse({}))}, ${json(DEFAULT_OFFERS)}, ${json(DEFAULT_WEIGHTS)}, 6` +
    `) ON CONFLICT (name) DO NOTHING;`,
  "",
);

mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}setup.sql`, parts.join("\n"));
console.log(`Wrote ${outDir}setup.sql`);
